services:
  bookapi:
    container_name: 'django-api'
    image: '${DJANGO_TUTORIAL_API_IMAGE}'
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/store/staticfiles/
      - media_volume:/store/mediafiles/
    expose:
      - 80
    env_file:
      - .env

  nginx:
    container_name: 'nginx'
    image: '${DJANGO_TUTORIAL_NGINX_IMAGE}'
    ports:
      - 80:80
    volumes:
      - static_volume:/store/staticfiles/
      - media_volume:/store/mediafiles/
    env_file:
      - .env

volumes:
  static_volume:
  media_volume:
