name: Create vercel preview URL on pull request

on:
    pull_request:
        branches: [main, master]

permissions:
    pull-requests: write

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.7
              with:
                  sparse-checkout: |
                      frontend/allsafe
            # Set up Vercel Action
            - uses: amondnet/vercel-action@v25.2.0
              id: vercel-deploy
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

            # Output the Vercel Preview URL
            - name: Show preview URL
              run: |
                  echo ${{ steps.vercel-deploy.outputs.preview-url }}
